pluginManagement {
    includeBuild('TVBox-media/build-logic-settings')
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
}

plugins {
    id 'gradlebuild.media3-settings-logic'
    id "org.gradle.toolchains.foojay-resolver-convention" version "1.0.0"
}

// Resolve Media3 coordinates exclusively from our local fork.
includeMedia3.execute(file('TVBox-media'))

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        google()
        flatDir { dirs "$rootDir/app/libs" }
        maven { url = "https://jitpack.io" }
    }
}

include ':app'
include ':catvod'
include ':chaquo'
include ':quickjs'
rootProject.name = "TV"
